### ISSUE TITLE
Make bot aware of timezones

### ISSUE THREAD

**Issue by mdmccoy** [mdmccoy/420bot#1]
The scheduler runs off of system time, which was cool when the server was on the same time zone as I was. But now that it's running on EC2, that server is on UTC time and the bot sends out a message four hours early. So lets make it aware of the time zone, and maybe take a preferred timezone in a config file, or something like that.

**Comment by andey** [comment]
![proof](https://i.imgur.com/mIv1FRl.png)

I'm having that problem to, as you can see from the screenshot, the 420 bot is not posting at 4:20, but instead 2:20.

**Comment by mdmccoy** [comment]
I'm thinking I'll add something like `config.yaml`, that allows you to specify a timezone. I can also add things like the channel you want to post to, or any other customizations that come down the line. Thoughts?

**Comment by mdmccoy** [comment]
First approach to this in https://github.com/mdmccoy/420bot/pull/3
